### ISSUE TITLE
Write a tutorial for instance-based evaluators

### ISSUE THREAD

**Issue by just1ngray** [just1ngray/pyfig#16]
An evaluator's `.name()` method returns a string. This string must be unique among the other evaluators being used, but it can also be created dynamically.

E.g.,

```python
class DemoEvaluator(AbstractEvaluator):
    def __init__(self, *, replacement: str="null"):
        self._replacement = replacement

    def name(self) -> str:
        return f"demo-{self._replacement}"

    def evaluate(self, value: str):
        return self._replacement
```

With such an evaluator we could define multiple.

```yaml
evaluators:
  custom_eval.DemoEvaluator:
    replacement: one
  custom_eval.DemoEvaluator:
    replacement: two
```

And then it'd be capable of substituting the following string, for example:

```
IN:  "${{demo-one}} / ${{demo-two}}"
OUT: "one / two"
```
